// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using vm_manager;

#nullable disable

namespace vm_manager.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("vm_manager.Models.PrivateKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Passphrase")
                        .HasColumnType("text");

                    b.Property<string>("PrivateKeyString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PublicKeyString")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PrivateKeys");
                });

            modelBuilder.Entity("vm_manager.Models.Server", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Servers");
                });

            modelBuilder.Entity("vm_manager.Models.ServerAuthentication", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Password")
                        .HasColumnType("text");

                    b.Property<Guid?>("PrivateKeyId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ServerId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("PrivateKeyId");

                    b.HasIndex("ServerId")
                        .IsUnique();

                    b.ToTable("ServerAuthentications");
                });

            modelBuilder.Entity("vm_manager.Models.ServerAuthentication", b =>
                {
                    b.HasOne("vm_manager.Models.PrivateKey", "PrivateKey")
                        .WithMany()
                        .HasForeignKey("PrivateKeyId");

                    b.HasOne("vm_manager.Models.Server", "Server")
                        .WithOne("ServerAuthentication")
                        .HasForeignKey("vm_manager.Models.ServerAuthentication", "ServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("PrivateKey");

                    b.Navigation("Server");
                });

            modelBuilder.Entity("vm_manager.Models.Server", b =>
                {
                    b.Navigation("ServerAuthentication");
                });
#pragma warning restore 612, 618
        }
    }
}
